export default {
  FETCH_ISSUES: 'FETCH_ISSUES',
  FETCH_TYPES: 'FETCH_TYPES',
  FETCH_STATUS: 'FETCH_STATUS',
  EDIT_ISSUE: 'EDIT_ISSUE',
  DELETE_ISSUE: 'DELETE_ISSUE',
  ADD_ISSUE: 'ADD_ISSUE',

  FETCH_USERS: 'FETCH_USERS',
  FETCH_GROUPS: 'FETCH_GROUPS',
  SIGNUP_USER: 'SIGNUP_USER',

  FETCH_HISTORY: 'FETCH_HISTORY',

  CLICKED_SIGNUP: 'CLICKED_SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  CLICKED_LOGIN: 'CLICKED_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'SIGNUP_FAIL',

  CLICKED_LOGOUT: 'CLICKED_LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};
